In [1]:
import torch

# Function Usage

### abs

In [2]:
a = torch.tensor([-2,-1,0,1,3])
a.abs(), a

(tensor([2, 1, 0, 1, 3]), tensor([-2, -1,  0,  1,  3]))

In [3]:
a = torch.tensor([-2,-1,0,1,3])
torch.abs(a, out=a), a

(tensor([2, 1, 0, 1, 3]), tensor([2, 1, 0, 1, 3]))

### abs_

In [4]:
a = torch.tensor([-2,-1,0,1,3])
a.abs_(), a

(tensor([2, 1, 0, 1, 3]), tensor([2, 1, 0, 1, 3]))

### absolute

In [5]:
torch.absolute(torch.tensor([-1,2]))

tensor([1, 2])

### acos

In [6]:
torch.acos(torch.tensor(-1))

tensor(3.1416)